services:
  - type: web
    name: tournament-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: streamlit run TournamentPlayersV9.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
